# Generated by Django 4.2.10 on 2024-03-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_stock_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productss',
        ),
    ]
