# Generated by Django 4.2.10 on 2024-03-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
